[build]
  publish = "dashboard"

[[redirects]]
  from = "/api/*"
  to = "https://TU-BACKEND.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/dashboard.html"
  status = 200