# Configuración para Render
services:
  - type: web
    name: crm-agente
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Configurar en el panel de Render con tu cadena de conexión de MongoDB Atlas
      - key: JWT_SECRET
        sync: false # Define un secreto fuerte en Render
    plan: free
